version: '3'
services:
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
 
  web:
    build: . 
    ports:
      - "3000:3000"